### PR TITLE
libavfilter/vf_python: Add video python filter

### PR DESCRIPTION
**Pull request by wenbinc-Bin**
Now many image algorithms are implemented in python. Add a filter that can call python script to process video frames. User need to pass script name, filter function and init function ( optional) to python filter. AVFrame will be transferred to a Tuple of numpy.ndarray and be passed to python script.

for example we have python script
/****ffmpeg-python.py****/
offset = 0
def init(init_str=None):
  global offset
  offset = int(init_str)

def filter_func(frame):
  for plane in frame:
    plane += offset
  return frame
/******end file************/

Add the path of script file into environment variable PYTHONPATH. we can call ffmpeg:
ffmpeg -i input.264 -vf format=rgb24, \
  video_python=module=ffmpeg-python:init_func=init:init_param="10": \
  filter_func=filter_func output.mp4

Which adds offset to each pixel of the frame.

### CODE REVIEW

**Comment by xhaihao** [comment]
s/algrithms/algorithms and s/transfered/transferred in the commit log

**Comment by xhaihao** [comment]
./configure --enable-python worked but make failed
libavfilter/vf_python.c:54:10: fatal error: numpy/arrayobject.h: No such file or directory
   54 | #include "numpy/arrayobject.h"
      |          ^~~~~~~~~~~~~~~~~~~~~

**Comment by wenbinc-Bin** [comment]
> ./configure --enable-python worked but make failed libavfilter/vf_python.c:54:10: fatal error: numpy/arrayobject.h: No such file or directory 54 | #include "numpy/arrayobject.h" | ^~~~~~~~~~~~~~~~~~~~~

you need to "pip install numpy"

**Comment by wenbinc-Bin** [comment]
> ./configure --enable-python worked but make failed libavfilter/vf_python.c:54:10: fatal error: numpy/arrayobject.h: No such file or directory 54 | #include "numpy/arrayobject.h" | ^~~~~~~~~~~~~~~~~~~~~

I add to commit log and comment.

**Pull request closed without merging**
