### PR TITLE
Core scc decode

### PR DESCRIPTION
**Pull request by xhaihao**

### CODE REVIEW

**Comment by xhaihao** [comment]
Checks  passed.

**Comment by uartie** [comment]
vp8 tests enabled in CI since recent upstream fixes them (https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/eb6bb8f32fdc9be89cce65869dce9dd950e91be2).

You can rebase your PR to resolve recent CI check failures.

**Comment by xhaihao** [comment]
Thanks for reminding me, I will update it.

**Comment by uartie** [comment]
checks pass. close

**Pull request closed without merging**
