### PR TITLE
Qsvdec enhancement

### PR DESCRIPTION
**Pull request by lizhong1008**

### CODE REVIEW

**Comment by lizhong1008** [comment]
I found HEVC encoding case failed:
ffmpeg -init_hw_device qsv=qsv:hw -hwaccel qsv -filter_hw_device qsv -v debug -f rawvideo -pix_fmt p010le -s:v 192x200 -r:v 25 -i /opt/media/src/assets/otc-media/yuv/Allegro_HEVC_Main10_HT51_PROCESSING_12-CTB32_192x200@60Hz_1.0_P010.yuv -vf 'hwupload=extra_hw_frames=64' -an -c:v hevc_qsv -profile:v main10 -g 1 -bf 0 -slices 1 -b:v 500k -maxrate 500k -load_plugin hevc_hw -vframes 300 -y /opt/media/test-results/vaapi-fits/ffmpeg-qsv-iHD/0bf94d5a-1d55-11e9-8a7d-0242ac110002_0/_0.test.ffmpeg-qsv.encode.hevc/Allegro_HEVC_Main10_HT51_PROCESSING_12-CTB32_192x200_60Hz_1_0-main10-500-1-1-0-25.h265 (pid: 770))

But it works well on my side. This PR haven't changed anything relative to encoding and hwdownload, and I found similar failure in PR https://github.com/intel-media-ci/ffmpeg/pull/11. So l think maybe it is a iHD driver (or MSDK) regression (I haven't updated iHD/MSDK to latest).

And another new failure issue is mjpeg decoding:
ffmpeg -hwaccel qsv -hwaccel_device /dev/dri/renderD128 -v verbose -c:v mjpeg_qsv -i /opt/media/src/assets/otc-media/mjpeg/1080p_blue_sky.mjpg -pix_fmt yuv420p -f rawvideo -vsync passthrough -vframes 5 -y /opt/media/test-results/vaapi-fits/ffmpeg-qsv-iHD/0bf94d5a-1d55-11e9-8a7d-0242ac110002_0/_0.test.ffmpeg-qsv.decode.jpeg/bluesky_1920x1080_I420.yuv

Yes, mjpeg decoding is added in this PR. But just like other decoding case, we need using hwdownload to load to system memory:
ffmpeg -hwaccel qsv -hwaccel_device /dev/dri/renderD128 -v verbose -c:v mjpeg_qsv -i 1080p_blue_sky.mjpg -vf "hwdownload,format=nv12" -pix_fmt yuv420p -f rawvideo -vsync passthrough test.yuv

@uartie , could you please add comments?

**Comment by uartie** [comment]
@lizhong1008 I will fix the mjpeg decode test.

Encode tests always _decode_ the "encoded" file to calculate a PSNR.  And the hevc encode tests are failing in the "decode" step for this pull-request.

All tests are passing fine with pure latest mainline stack.  Other pull-requests are passing tests with latest mainline dependencies, too.

So I can only conclude that something in this pull-request causes the regressions.  Same for #11.

**Comment by uartie** [comment]
This is confusing... there seems to be several patches here duplicated by #26 and #32.  Please provide a better separation of scope and avoid duplication in PR's.  Otherwise, it's just too disorganized.

**Comment by lizhong1008** [comment]
@uartie ， PR https://github.com/intel-media-ci/ffmpeg/pull/32 has a dependency on this one. Let's close this https://github.com/intel-media-ci/ffmpeg/pull/26 and this one (will consider to rebase/reopen it if necessary ).

**Pull request closed without merging**
