### PR TITLE
lavu/fifo: fix regression

### PR DESCRIPTION
**Pull request by xhaihao**
offset_w might be updated after growing the FIFO

Fix ticket #9630

Signed-off-by: Haihao Xiang <haihao.xiang@intel.com>

### CODE REVIEW

**Comment by uartie** [comment]
LGTM.  This fixes it for me.  Nice Job!

**Comment by uartie** [comment]
Other test failures caused by https://trac.ffmpeg.org/ticket/9629... unrelated.

**Review by uartie — APPROVED** [review]
lgtm

**Comment by uartie** [comment]
maybe change commit title to be less generic... e.g. "lavu/fifo: offset_w should capture FIFO growth"

**Comment by uartie** [comment]
> maybe change commit title to be less generic... e.g. "lavu/fifo: offset_w should capture FIFO growth"

No worries though since it is already submitted to ML.

**Comment by xhaihao** [comment]
> maybe change commit title to be less generic... e.g. "lavu/fifo: offset_w should capture FIFO growth"

Sorry I didn't see this comment when I submitted https://patchwork.ffmpeg.org/project/ffmpeg/patch/20220208054734.14166-1-haihao.xiang@intel.com/

**Comment by uartie** [comment]
> > maybe change commit title to be less generic... e.g. "lavu/fifo: offset_w should capture FIFO growth"
> 
> Sorry I didn't see this comment when I submitted https://patchwork.ffmpeg.org/project/ffmpeg/patch/20220208054734.14166-1-haihao.xiang@intel.com/

no worries. lgtm

**Pull request closed without merging**
