### PR TITLE
Qsv vaapi map

### PR DESCRIPTION
**Pull request by wenbinc-Bin**
This is qsv part of 3dinput. The most important part are already submited to upstream. This patchset connect vaapi and qsv.

### CODE REVIEW

**Comment by wenbinc-Bin** [comment]
@xhaihao @xuguangxin @feiwan1 Could you please help me to review these patches.
Thanks
Wenbin

**Comment by xhaihao** [comment]
deriving vaapi device from qsv device is resolved in http://ffmpeg.org/pipermail/ffmpeg-devel/2021-August/283229.html

**Comment by wenbinc-Bin** [comment]
@xhaihao Thanks for your infomation. 
I just tried the patch. when I run command
`ffmpeg -v verbose -hwaccel qsv -c:v h264_qsv -i input_1080p.264 -vf "hwmap=derive_device=vaapi,format=vaapi,scale_vaapi=w=1920:h=1080,hwdownload,format=nv12" -f rawvideo output.yuv`
It report a segmentation fault. As what you said in mailing list, it seems to be a double free problem, but the author haven't submit new patch to fix it.

**Comment by wenbinc-Bin** [comment]
This softworkz's patch can fix my first issue. My other two patches are still needed.

**Comment by xhaihao** [comment]
> @xhaihao Thanks for your infomation.
> I just tried the patch. when I run command
> `ffmpeg -v verbose -hwaccel qsv -c:v h264_qsv -i input_1080p.264 -vf "hwmap=derive_device=vaapi,format=vaapi,scale_vaapi=w=1920:h=1080,hwdownload,format=nv12" -f rawvideo output.yuv`
> It report a segmentation fault. As what you said in mailing list, it seems to be a double free problem, but the author haven't submit new patch to fix it.

I provided a way in http://ffmpeg.org/pipermail/ffmpeg-devel/2021-August/283999.html to fix the double free issue. You may have a try if interested in.

**Comment by wenbinc-Bin** [comment]
> > @xhaihao Thanks for your infomation.
> > I just tried the patch. when I run command
> > `ffmpeg -v verbose -hwaccel qsv -c:v h264_qsv -i input_1080p.264 -vf "hwmap=derive_device=vaapi,format=vaapi,scale_vaapi=w=1920:h=1080,hwdownload,format=nv12" -f rawvideo output.yuv`
> > It report a segmentation fault. As what you said in mailing list, it seems to be a double free problem, but the author haven't submit new patch to fix it.
> 
> I provided a way in http://ffmpeg.org/pipermail/ffmpeg-devel/2021-August/283999.html to fix the double free issue. You may have a try if interested in.

Works for me. It can take place of my first patch. Should I wait for him to submit the V3 patch?

**Comment by wenbinc-Bin** [comment]
Any feedback for my other two patches? 
If no, I will submit to upstream in the next day.

**Comment by xuguangxin** [comment]
@wenbinc-Bin  thanks for your patch. 
This patch is very important, please get @xhaihao 's approval firstly.

**Comment by wenbinc-Bin** [comment]
> @wenbinc-Bin thanks for your patch.
> This patch is very important, please get @xhaihao 's approval firstly.

I am waiting a patch from softworkz. His patch can replace my first one.
This patchset is submitted to cartwheel temporarily, and will be updated later when softworkz merge his patch to upstream.

**Comment by wenbinc-Bin** [comment]
This is reviewed as part of PR: [https://github.com/intel-media-ci/cartwheel-ffmpeg/pull/55](https://github.com/intel-media-ci/cartwheel-ffmpeg/pull/55). Close this one.

**Pull request closed without merging**
