### PR TITLE
Pr qsv refactor

### PR DESCRIPTION
**Pull request by fulinjie**
PR checks for refactors and vpp prompts.

### CODE REVIEW

**Comment by fulinjie** [comment]
hi @xuguangxin @xhaihao, seems that not all checks are passed(at least focal and groovy), would you please help to take a look?

**Comment by xhaihao** [comment]
@fulinjie I updated my patches in https://github.com/intel-media-ci/ffmpeg/pull/328, could you have a try again?

**Comment by fulinjie** [comment]
> @fulinjie I updated my patches in #328, could you have a try again?

Updated and started to recheck.

**Comment by uartie** [comment]
tests pass. close

**Pull request closed without merging**
