### PR TITLE
libavutil/hwcontext_qsv.c:Fill pixels for realigned frame in qsv

### PR DESCRIPTION
**Pull request by zhangyuankun-star**
According to MediaSDK doc, app needs to fill the extend area caused by alignment,
So I fill the copy of pixel on the border.
MediaSDK doc: https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#encoding-procedures,
"It is the application's responsibility to fill pixels outside of crop window when it is smaller than frame to be encoded.
Especially in cases when crops are not aligned to minimum coding block size (16 for AVC, 8 for HEVC and VP9)."

Signed-off-by: Zhang Yuankun <yuankunx.zhang@intel.com>

### CODE REVIEW

**Comment by zhangyuankun-star** [comment]
@xhaihao @xuguangxin Hi，Haihao & Guangxin,can you review this for me?

**Comment by xhaihao** [comment]
Extending data is required for encoding only, It seems your patch will impact other QSV operations.

**Comment by uartie** [comment]
@zhangyuankun-star any update?

**Comment by uartie** [comment]
@xhaihao @xuguangxin can you follow-up with @zhangyuankun-star about this patch... there has been no response from @zhangyuankun-star

**Comment by zhangyuankun-star** [comment]
I'm sorry I didn't reply in time. I haven't come up with a good solution to the problem raised by haihao. I'll close this PR first, and I'll submit it again after I solve the problem. thanks！

**Pull request closed without merging**
