### PR TITLE
avcodec/vaapi_av1: correct tile data offset

### PR DESCRIPTION
**Pull request by feiwan1**
Signed-off-by: Fei Wang <fei.w.wang@intel.com>

### CODE REVIEW

**Comment by xuguangxin** [comment]
@xhaihao , could you help review this?
thanks

**Comment by feiwan1** [comment]
I have tested this patch with 10+ tile clips, all them can pass. And Yuankun helped to test this pr with our full test case, no regression.

So we can consider to upstream this patch. @xhaihao @xuguangxin Can you help review this? Thanks.

**Comment by xuguangxin** [comment]
@xhaihao  are we good to send this to community?
@feiwan1 , did you tried mp4 and webm?

thanks

**Comment by xhaihao** [comment]
It seems for me that this patch works around a potential issue in the driver (Maybe the driver didn't follow the offset setting to update the content of the slice buffer).  Could you double-check how the driver update the content of AV1 slice when calling vaCreateBuffer() ?

**Comment by feiwan1** [comment]
> It seems for me that this patch works around a potential issue in the driver (Maybe the driver didn't follow the offset setting to update the content of the slice buffer). Could you double-check how the driver update the content of AV1 slice when calling vaCreateBuffer() ?

Media-driver seems doesn't check the offset in slice parameter when create slice data buffer.
https://github.com/intel/media-driver/blob/12ca7a4c415eb7309814e7968df21c392cd469d3/media_driver/linux/common/codec/ddi/media_ddi_decode_base.cpp#L941

https://github.com/intel/media-driver/blob/12ca7a4c415eb7309814e7968df21c392cd469d3/media_driver/linux/common/codec/ddi/media_ddi_decode_base.cpp#L1101

**Comment by feiwan1** [comment]
> @xhaihao are we good to send this to community?
> @feiwan1 , did you tried mp4 and webm?
> 
> thanks

I will make some mp4 and webm clips to test it.

**Comment by xuguangxin** [comment]
> > It seems for me that this patch works around a potential issue in the driver (Maybe the driver didn't follow the offset setting to update the content of the slice buffer). Could you double-check how the driver update the content of AV1 slice when calling vaCreateBuffer() ?
> 
> Media-driver seems doesn't check the offset in slice parameter when create slice data buffer.
> https://github.com/intel/media-driver/blob/12ca7a4c415eb7309814e7968df21c392cd469d3/media_driver/linux/common/codec/ddi/media_ddi_decode_base.cpp#L941
> 
> https://github.com/intel/media-driver/blob/12ca7a4c415eb7309814e7968df21c392cd469d3/media_driver/linux/common/codec/ddi/media_ddi_decode_base.cpp#L1101

@feiwan1 , from the API, we need the driver to use the offset, right?

**Comment by feiwan1** [comment]
Close this PR, will push a new one which fix the issue by change data size when create slice data buffer.

**Pull request closed without merging**
