### PR TITLE
libavutil/hwcontext_qsv: fix a bug when malloc handle_pairs_internal

### PR DESCRIPTION
**Pull request by wenbinc-Bin**
We use nb_surfaces to assign surface to handle_pairs_internal so we
need to use nb_surfaces to malloc handle_pairs_internal.

Signed-off-by: Wenbin Chen <wenbin.chen@intel.com>

### CODE REVIEW

**Comment by xhaihao** [comment]
Does qsv/d3d11va  need the same change ?

**Comment by xhaihao** [comment]
@galinart  src_ctx->initial_pool_size is used when allocating s->handle_pairs_internal and s->surfaces_internal for d3d11va, however src_ctx->initial_pool_size is used for s->handle_pairs_internal and src_hwctx->nb_surfaces is used for s->surfaces_internal if device type is dxva2 or vaapi.  Could you confirm which is right ?

**Comment by wenbinc-Bin** [comment]
> Does qsv/d3d11va need the same change ?

d3d11va doesn't has nb_surfaces var in its public FrameContext structure, so I only changed dxva and vaapi.

**Comment by wenbinc-Bin** [comment]
@xhaihao @galinart I add nb_surfaces to AVD3D11VAFramesContext so it align to vaapi and dxva. Please help to review the new patches. 
Thanks

**Comment by wenbinc-Bin** [comment]
@xhaihao @galinart Any comments on this PR?
Thanks

**Comment by wenbinc-Bin** [comment]
Any comments on this PR? If no, I will submit to upstream.

**Comment by xuguangxin** [comment]
could you provide some failed comandline in the commit log to explain why we need this change?

**Comment by wenbinc-Bin** [comment]
ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i input.264 -vf "hwmap=derive_device=qsv,format=qsv" -c:v h264_qsv output.264

This commandline will report "core dumped". This PR can fix this error, but the command line still doesn't work. This PR https://github.com/intel-media-ci/ffmpeg/pull/461 is needed to make commandline works.

**Comment by xuguangxin** [comment]
thank @wenbinc-Bin , please add this commandline to your commit log (make it simpler if possible). and when you send to upstream please send those patches together. thanks

**Comment by wenbinc-Bin** [comment]
I include nyanmisaka's patches into this PR. Any more comments?

**Comment by wenbinc-Bin** [comment]
@xhaihao @xuguangxin @feiwan1 Any comments on this PR? I am ready to submit the patchset.

**Review by xhaihao — APPROVED** [review]

**Pull request closed without merging**
