### PR TITLE
libavfilter/vf_vpp_qsv: Fix a timestamp bug when framerate is not set

### PR DESCRIPTION
**Pull request by wenbinc-Bin**
If user doesn't set framerate when he creates a filter, the filter uses default framerate {0, 1}. This causes error when setting timebase to 1/framerate. Now change it to pass inlink->time_base to outlink when framerate is not set.
This patch fixes ticket: #10476 #10468

### CODE REVIEW

**Comment by xhaihao** [comment]
@wenbinc-Bin  Please check the error in pre-check

**Comment by wenbinc-Bin** [comment]
> @wenbinc-Bin Please check the error in pre-check

I rerun the check and the failure disappear.

**Review by xhaihao — APPROVED** [review]
LGTM

**Comment by wenbinc-Bin** [comment]
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20230815083425.2648894-1-wenbin.chen@intel.com/

**Pull request closed without merging**
