### PR TITLE
libavcodec/qsvenc: expose only supported options

### PR DESCRIPTION
**Pull request by dvrogozh**
vp9, hevc, avc, mpeg2 QSV encoders inherit common list
of options (QSV_COMMON_OPTS) while bunch of options is not
actually supported by current qsv code. The only codec which
supportes everything is avc, followed by hevc, while vp9 and
mpeg2 significantly fall behind. This creates difficulties
for the users to use qsv encoders. This patch fixes options
list for encoders leaving only those which are actually
supported.

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

### CODE REVIEW

**Comment by wenbinc-Bin** [comment]
LGTM. Thanks!

**Review by xhaihao — APPROVED** [review]

**Comment by xhaihao** [comment]
@uartie @Bin-CI could you please check why the pre-check doesn't complete for this PR?

**Comment by uartie** [comment]
> @uartie @Bin-CI could you please check why the pre-check doesn't complete for this PR?

Looks like it completed.  Just not sure why it didn't get reported back to GitHub.  I will trigger again.

**Comment by uartie** [comment]
submitted to upstream ML

**Pull request closed without merging**
