### PR TITLE
D3d12va

### PR DESCRIPTION
**Pull request by tong1wu**

### CODE REVIEW

**Comment by Andarwinux** [comment]
Hello, is it possible for ffmpeg d3d12va to work on linux (wsl)? Just like mesa d3d12.

**Comment by xhaihao** [comment]
You may use d3d12va in wsl, however you can't use it in native Linux.

**Comment by Andarwinux** [comment]
I'm getting an error when compiling ffmpeg d3d12va with DirectX-Headers for wsl, the reason seems d3d12va requires windows.h which doesn't exist on linux.

```
check_type windows.h d3d12.h ID3D12Device
test_code cc windows.h d3d12.h ID3D12Device v
    2   #include <d3d12.h>
check_type windows.h d3d12video.h ID3D12VideoDecoder
test_code cc windows.h d3d12video.h ID3D12VideoDecoder v
    2   #include <d3d12video.h>
ERROR: d3d12va requested, but not all dependencies are satisfied: dxva_h ID3D12Device ID3D12VideoDecoder
```

**Comment by xhaihao** [comment]
@Andarwinux What I meant is we may run a application with d3d12va support in wsl. I don't know whether we can build FFmpeg with d3d12va support in wsl.

**Comment by tong1wu** [comment]
> I'm getting an error when compiling ffmpeg d3d12va with DirectX-Headers for wsl, the reason seems d3d12va requires windows.h which doesn't exist on linux.
> 
> ```
> check_type windows.h d3d12.h ID3D12Device
> test_code cc windows.h d3d12.h ID3D12Device v
>     2   #include <d3d12.h>
> check_type windows.h d3d12video.h ID3D12VideoDecoder
> test_code cc windows.h d3d12video.h ID3D12VideoDecoder v
>     2   #include <d3d12video.h>
> ERROR: d3d12va requested, but not all dependencies are satisfied: dxva_h ID3D12Device ID3D12VideoDecoder
> ```

This patch set can be built in MingW64 with MSVC compiler and native Windows headers. And they are adding d3d12 headers in MingW environment which benefits gcc compiling. See https://github.com/mingw-w64/mingw-w64/issues/24

**Comment by Andarwinux** [comment]
That's a shame, wsl currently needs vaapi on d3d12 for hwaccel, which is a bit slow, I had hoped ffmpeg d3d12va could be run directly on linux without vaon12, thus gaining native performance. But thanks for your info.

**Comment by tong1wu** [comment]
> That's a shame, wsl currently needs vaapi on d3d12 for hwaccel, which is a bit slow, I had hoped ffmpeg d3d12va could be run directly on linux without vaon12, thus gaining native performance. But thanks for your info.

Vaon12 decoder has some performance issue before but it's fixed now. You could try some new versions.  FFmpeg d3d12va can be run on wsl in 2 ways.
1. Compiled as a Windows binary ffmpeg.exe. You can run .exe on WSL with no doubt.
2. Compiled as a Linux binary. It depends on configuring the ffmpeg project in the right way, making it find the right include path and Linux binaries such as libd3d12.so. We haven't done this yet, maybe in the future.

**Comment by tong1wu** [comment]
Merged into upstream. Closed.

**Pull request closed without merging**
