### PR TITLE
D3d12va (for testing)

### PR DESCRIPTION
**Pull request by tong1wu**

### CODE REVIEW

**Comment by oscarbg** [comment]
Curious if you may add in this or a separate patch also ENCODE d3d12va support.. in latest agility sdk they provide same codecs as decode, i.e. up to av1 encode support also..

**Comment by tong1wu** [comment]
> Curious if you may add in this or a separate patch also ENCODE d3d12va support.. in latest agility sdk they provide same codecs as decode, i.e. up to av1 encode support also..

Yes we are currently working on encoder part and this may take a while.

**Comment by tong1wu** [comment]
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20230602080701.1754-1-tong1.wu@intel.com/ Close this pr.

**Comment by oscarbg** [comment]
@tong1wu thanks, good to know!

**Pull request closed without merging**
