### PR TITLE
Pr vaapi 444/444_10

### PR DESCRIPTION
**Pull request by fulinjie**
YUV444 blocked by:
https://github.com/intel/media-driver/issues/577

YUV444_10 blocked by same issue in GST-VAAPI:
https://github.com/intel/media-driver/issues/431

### CODE REVIEW

**Comment by uartie** [comment]
This seems to break ffmpeg-vaapi mpeg2 decode test cases

**Comment by fulinjie** [comment]
Will update the patch set according to the comments from community and some pix_fmt support for packed format.
By the way, I got the check result for qsv in intel/ci/ubuntu/bionic/pr/check.
where can I get the result for ffmpeg-vaapi?
Thanks in advance.

**Comment by uartie** [comment]
The intel/ci/ubuntu/bionic/pr/check compiles and tests both -vaapi and -qsv, so I'm not sure what you mean.

**Comment by uartie** [comment]
> The intel/ci/ubuntu/bionic/pr/check compiles and tests both -vaapi and -qsv, so I'm not sure what you mean.

On the "Build Overview" tab/page, there should be test summaries (near the bottom) for all -vaapi and -qsv (on both iHD and i965).

**Comment by fulinjie** [comment]
> > The intel/ci/ubuntu/bionic/pr/check compiles and tests both -vaapi and -qsv, so I'm not sure what you mean.
> 
> On the "Build Overview" tab/page, there should be test summaries (near the bottom) for all -vaapi and -qsv (on both iHD and i965).

Thanks Artie, found the right entry for the vaapi result.
Used to check the results by test suit, it seems that we should choose the exact test report (vaapi/qsv on exact platform) first.

**Comment by fulinjie** [comment]
New patch set provided:
https://github.com/intel-media-ci/ffmpeg/pull/41
Closed.

**Pull request closed without merging**
