### PR TITLE
hevc parser modify and update FATE

### PR DESCRIPTION
**Pull request by fulinjie**

### CODE REVIEW

**Comment by fulinjie** [comment]
https://patchwork.ffmpeg.org/patch/11356/

**Comment by uartie** [comment]
V4: https://patchwork.ffmpeg.org/patch/11703/

**Comment by uartie** [comment]
Our tests have been updated to specify rc_mode option in ffmpeg commands.  The rc_mode option requires upstream commit f4d7bd6cdbcf.  So please rebase this pull-request on top of latest master branch with your latest patch version.

**Comment by fulinjie** [comment]
@uartie all PRs updated, and "Allow edits from maintainers" option is enabled .
Thanks.

**Comment by uartie** [comment]
Closing. Upstream review appears to have stalled on v4.  Please open a new PR if v5 is needed.

**Pull request closed without merging**
