### PR TITLE
lavc/qsvdec: resolution check for reinit without alignment

### PR DESCRIPTION
**Pull request by fulinjie**
resolution check for reinit without alignment based on 16.

Signed-off-by: Linjie Fu <linjie.fu@intel.com>

### CODE REVIEW

**Comment by uartie** [comment]
Was this submitted to the upstream ML?  I can't seem to find it.

**Comment by fulinjie** [comment]
Patch is here, and modified a little bit (patch's name, for example):
https://patchwork.ffmpeg.org/patch/12059/

**Comment by zhoujd** [comment]
CI has issues to build this PR, 
https://media-ci.ostc.intel.com/build/311010/step_status

Can you try to rebase your this patch on the latest master branch ?

**Comment by uartie** [comment]
checks passed.  closing

**Pull request closed without merging**
