### PR TITLE
Add pad_vaapi & drawbox_vaapi filters

### PR DESCRIPTION
**Pull request by xhaihao**

### CODE REVIEW

**Comment by wenbinc-Bin** [comment]
Do we need to draw outer_frame every time? If we draw outer_frame only once and reuse it, will it be better?

**Comment by xhaihao** [comment]
> Do we need to draw outer_frame every time? If we draw outer_frame only once and reuse it, will it be better?

Thanks for the comment, I fixed it in the new version.

**Comment by wenbinc-Bin** [comment]
LGTM. Thanks

**Comment by xhaihao** [comment]
https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=11175

**Pull request closed without merging**
