### PR TITLE
[V7]Scc dec

### PR DESCRIPTION
**Pull request by feiwan1**

### CODE REVIEW

**Comment by feiwan1** [comment]
submit with https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=8314.

**Comment by feiwan1** [comment]
https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=8331

**Review by xhaihao — DISMISSED** [review]
LGTM

**Comment by feiwan1** [comment]
https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=8391

**Pull request closed without merging**
