### PR TITLE
Pr mctf

### PR DESCRIPTION
**Pull request by fulinjie**
First patch: cope with MFX ErrorMoreData condition in VPP pipeline.

### CODE REVIEW

**Comment by fulinjie** [comment]
Patch 2/2: lavf/qsvvpp: add support for Motion Compensated Temporal Filter

**Comment by uartie** [comment]
Why are there so many "merge" commits included here and other PRs?  You should be using "git rebase" to sync your topic tree with intel-media-ci/master.

**Comment by fulinjie** [comment]
will follow, thanks uartie.

**Comment by fulinjie** [comment]
patch:
https://patchwork.ffmpeg.org/patch/11739/

**Comment by linjiefu** [comment]
https://github.com/intel/media-driver/issues/498

**Comment by fulinjie** [comment]
close currently.

**Pull request closed without merging**
