### PR TITLE
lavc/qsvenc: add tile encoding support for VP9

### PR DESCRIPTION
**Pull request by xhaihao**
Add -tile_rows and -tile_cols options to specify the number of tile
rows and and columns

### CODE REVIEW

**Comment by uartie** [comment]
repeated word in commit message:  `rows **and and** columns`

**Comment by uartie** [comment]
Do other VP9e plugins and/or middleware support these options, too?  Seems we will need to create some test cases for this @focusluo.

**Comment by xhaihao** [comment]
> repeated word in commit message: `rows **and and** columns`

Thanks, I updated the commit in the new version.

**Comment by xhaihao** [comment]
> Do other VP9e plugins and/or middleware support these options, too? Seems we will need to create some test cases for this @FocusLuo.

We may add it to gst-msdk if needed.

**Review by uartie — APPROVED** [review]
LGTM

**Comment by uartie** [comment]
> > Do other VP9e plugins and/or middleware support these options, too? Seems we will need to create some test cases for this @FocusLuo.
> 
> We may add it to gst-msdk if needed.

You mean ffmpeg-qsv?

**Comment by uartie** [comment]
> > > Do other VP9e plugins and/or middleware support these options, too? Seems we will need to create some test cases for this @FocusLuo.
> > 
> > 
> > We may add it to gst-msdk if needed.
> 
> You mean ffmpeg-qsv?

Oh, sorry, you mean add the options to gst-msdk plugin :).  Got it.  It's not required since we can implement separate cases for ffmpeg-qsv.

**Comment by uartie** [comment]
> > > > Do other VP9e plugins and/or middleware support these options, too? Seems we will need to create some test cases for this @FocusLuo.
> > > 
> > > 
> > > We may add it to gst-msdk if needed.
> > 
> > 
> > You mean ffmpeg-qsv?
> 
> Oh, sorry, you mean add the options to gst-msdk plugin :). Got it. It's not required since we can implement separate cases for ffmpeg-qsv.

Was just curious if we already had support in other plugins.

**Comment by xhaihao** [comment]
> > > Do other VP9e plugins and/or middleware support these options, too? Seems we will need to create some test cases for this @FocusLuo.
> > 
> > 
> > We may add it to gst-msdk if needed.
> 
> You mean ffmpeg-qsv?

Sorry for misleading you, I answered your first question.

**Comment by xhaihao** [comment]
Upstream patch: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20211214070021.31672-1-haihao.xiang@intel.com/

**Pull request closed without merging**
