### PR TITLE
Pr trellis

### PR DESCRIPTION
**Pull request by fulinjie**
pre-patch test for VAAPI AVC Trellis support.

### CODE REVIEW

**Comment by lizhong1008** [comment]
Please don't mix trellis patch with hevc parser issue fixing.

**Comment by fulinjie** [comment]
> Please don't mix trellis patch with hevc parser issue fixing.

Updated, thanks.

**Comment by fulinjie** [comment]
patch:
https://patchwork.ffmpeg.org/patch/11733/

**Comment by lizhong1008** [comment]
it depends on https://github.com/intel/libva/pull/272, @fulinjie please verify it works or not, and update it once the va patch merged.

**Comment by fulinjie** [comment]
Verified, it works. 
Will update after the patch being merged.

**Comment by uartie** [comment]
all checks passed. closing

**Pull request closed without merging**
