### PR TITLE
qsvenc: add the support of lookahead for CBR and VBR on Windows

### PR DESCRIPTION
**Pull request by guanjunz**
add the support of lookahead for CBR and VBR on Windows

### CODE REVIEW

**Comment by wenbinc-Bin** [comment]
@guanjunz  According to your change, LookAhead doesn't need extbrc. I tried on my side(DG2 env).  If I don't set extbrc the look_ahead_depth doesn't work. It only change the query result, but still output same video stream.

**Comment by guanjunz** [comment]
Hi Wenbin, Thanks for your comments. HW LPLA needs three conditions now. extbrc == 0 && lookaheaddepth > 0 && scenarioInfo=7.  this change would like to use extbrc=0 to distinguish from other two mode. Could you please have a try?
BTW, there are three kinds of LPLAs. 
VME(pre generation): lookahead depth > 0  (the default extbrc=-1)
VDEnc Extbrc: lookahead depth > 0 && extbrc =1
VDEnc HWbrc: lookahead depth > 0 && extbrc =0 && scenarioinfo =7

**Comment by guanjunz** [comment]
> @guanjunz According to your change, LookAhead doesn't need extbrc. I tried on my side(DG2 env). If I don't set extbrc the look_ahead_depth doesn't work. It only change the query result, but still output same video stream.

Hi Wenbin, Thanks for your comments. HW LPLA needs three conditions now. extbrc == 0 && lookaheaddepth > 0 && scenarioInfo=7. this change would like to use extbrc=0 to distinguish from other two mode. Could you please have a try?
BTW, there are three kinds of LPLAs.
VME(pre generation): lookahead depth > 0 (the default extbrc=-1)
VDEnc Extbrc: lookahead depth > 0 && extbrc =1
VDEnc HWbrc: lookahead depth > 0 && extbrc =0 && scenarioinfo =7

**Comment by wenbinc-Bin** [comment]
I tried on public VPL and it still doesn't work. I tried on inner VPL and it works but reports unsupported error. Does DG2 support hardware lpla? Should I change to inner media-driver as well?
Does av1 hw lpla need to set scenarioinfo to 7?

**Comment by xhaihao** [comment]
@guanjunz  could you add more description about this change in commit log ?

**Comment by guanjunz** [comment]
> @guanjunz could you add more description about this change in commit log ?

Hi Haihao, I will add more to description about it. Currently, it cannot achieve quality match as mfx_transcoder. I will identify the difference.

**Comment by xhaihao** [comment]
@guanjunz  May I close this PR ?

**Comment by guanjunz** [comment]
> @guanjunz May I close this PR ?

Sure. Thanks Haihao.

**Pull request closed without merging**
