### PR TITLE
fix some security issues

### PR DESCRIPTION
**Pull request by fulinjie**
Fix some value initialization issues.

### CODE REVIEW

**Comment by uartie** [comment]
Has this patch been submitted to upstream ML, yet?  If so, please provide link here (i.e. patchwork).

**Comment by fulinjie** [comment]
https://patchwork.ffmpeg.org/patch/10927/
https://patchwork.ffmpeg.org/patch/10926/
https://patchwork.ffmpeg.org/patch/10925/

**Comment by uartie** [comment]
It would be better if you submit exactly the same patches here (not a squashed version) as the ones submitted upstream.  Otherwise it's hard to identify/track them 1:1 across the different patch systems.

**Comment by fulinjie** [comment]
sure, got it.

**Comment by uartie** [comment]
FATE tests have been enabled in `intel/ci/ubuntu/bionic/pr/check`.  Please rebase this pull-request for latest FATE patch to fix compile issue.

**Comment by uartie** [comment]
> FATE tests have been enabled in `intel/ci/ubuntu/bionic/pr/check`. Please rebase this pull-request for latest FATE patch to fix compile issue.

Fixed.  It was a CI configuration issue.

**Comment by uartie** [comment]
Close this.  It seems the original PW series will be replaced by other evolved solutions

**Pull request closed without merging**
