### PR TITLE
lavfi/dnn: Error Specificity

### PR DESCRIPTION
**Pull request by shubhanshu02**
## Patch Set Description

This patchset improves the error specificity on all the patchsets from the GSoC project [Async Support for TensorFlow Backend in FFmpeg](https://summerofcode.withgoogle.com/projects/#5224576843251712).

- Builds on the patchset from PR #423, #425, and #427

**Objective**: Return Specific Error codes from the DNN Backend Functions

### Parts under this deliverable

- Add `DNN_GENERIC_ERROR` for errors related to the backend framework API-related errors.
- Use error codes from [libavutil/error.c](libavutil/error.c)

### Patches

41b15128ede7a041e51fc8de15735c79cab79e2c libavfilter: Prepare to handle specific error codes in DNN Filters
9f53605b93bf4cbc39b9a794cec64c1063d46cc8 lavfi/dnn: Error Specificity in Native Backend Layers
c3a2fe2ddb34ab4ff5ec00543bd03dbe50dd71a6 lavfi/dnn_io_proc: Return Specific Error Codes
9e219b76e2d745c937fbfff24810544ef68691b6 lavfi/dnn_backend_openvino: Return Specific Error Codes
4a498acbc4abd8092dff69e77b5fbff6b07159bc lavfi/dnn_backend_tf: Return Specific Error Codes
ec471f77dcc0f3b5fa34d71b328817a7ee9a505b lavfi/dnn_backend_native: Return Specific Error Codes
605cccb76e1087d6ee4611886cc7e3d77cf03ce3 lavfi/dnn_backend_common: Return specific error codes

### CODE REVIEW

**Comment by uartie** [comment]
Checks passed.  Any reviews needed?  If not, is it ready for upstream so we can close this?

**Comment by shubhanshu02** [comment]
@guoyejun sir?

**Comment by guoyejun** [comment]
sorry for the missing, I might need several other weeks to start the review.

**Comment by shubhanshu02** [comment]
No problem. Shall I close this PR for now or keep it open?

**Comment by shubhanshu02** [comment]
I saw all occurences of `av_mallocz_array()` were replaced by `av_calloc()` in 1ea365082318f06cd42a8b37dd0c7724b599c821. So corrected and rebased the branch with master.

**Pull request closed without merging**
